ALTER TABLE wallet ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE wallet_transaction ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE application ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE campaign ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
